### PR TITLE
Update init.lua

### PR DESCRIPTION
**Pull request by TomasJLuis**
I've added these functions to detect if player is placing torches in water.
Then you call iswet(pos) from 'on_place' and if it's true then avoid placing torch.

### CODE REVIEW

**Comment by HybridDog** [comment]
thanks for the idea
http://paste.ubuntu.com/10765842/

**Comment by BlockMen** [comment]
First: The Minetest styled torch should be usable as the "builtin" if wanted. So if you think this feature should be added to to Mt-styled aswell make a setting for it.

Second: Why don't you just check the node where the torch is gonna placed? Is there an example that would show a case where it would be neccessary to check more?

Third: Please don't open 3 Pull Requests for one topic. You can edit all files and THEN make a PR ;)

**Comment by TomasJLuis** [comment]
@HybridDog thank you. I think that there is a potencial problem with your solution: if you only check the above node you can still placing the torch in the first layer of water. ;P
@BlockMen 
First: of course.
Second: That was my initial intention but It didn't work... :/ I will check it again. May be I did some mistake the first time.
Third: I'm new at gitHub, sorry.

**Comment by HybridDog** [comment]
@TomasJLuis pointed_thing.above is the place where the torch appears, so you can only place it into air

**Comment by TomasJLuis** [comment]
@HybridDog yes you are right... I understood it wrong. Thank you for your clarification.
However I've been testing your solution  and I've found a failure (my solution have the same issue):
If you dig a block underwater and quickly place the torch in the same spot you are able to place the torch underwater.

But I think that I have found the way to fix it. I will do some more test before upload the new code.
Thank you again.

**Comment by TomasJLuis** [comment]
@HybridDog 
I've found the way to fix it:
`function iswet (pos)`
	`local pi = pos`
	`local p0 = {x = pos.x, y = pos.y + 1, z = pos.z}`
	`local p1 = {x = pos.x - 1, y = pos.y, z = pos.z}`
	`local p2 = {x = pos.x + 1, y = pos.y, z = pos.z}`
	`local p3 = {x = pos.x, y = pos.y, z = pos.z + 1}`
	`local p4 = {x = pos.x, y = pos.y, z = pos.z - 1}`
	`return iswater(pi) or iswater(p0) or iswater(p1) or iswater(p2) or iswater(p3) or iswater(p4)`
`end`

I know it's more complicated but it works in more cases.
However this cause another issue: you cannot place torches at the block just after flowing water. Any idea how to fix it.

**Comment by BlockMen** [comment]
@TomasJLuis IIRC the water level is stored in param2

**Comment by HybridDog** [comment]
>But that wouldnt fix the problem of <8 nodes flowing water

why not?
https://github.com/HybridDog/stronger_water/blob/master/init.lua#L63
https://github.com/HybridDog/builtin_item/blob/master/init.lua

**Comment by TomasJLuis** [comment]
@BlockMen @HybridDog Thank you both. :+1:

**Comment by TomasJLuis** [comment]
Ok, I've updated the code to add `param2 > 0` checking, so now you can place torches at the end of a flowing water.
You can still place a torch under the last flowing water block, howerver, using `strong_water` from @HybridDog with a little change to detect this torches (drawtype = 'mesh' and node.groups.torch ~= 0) the torch will be removed.

**Comment by TomasJLuis** [comment]
@BlockMen Final version (I hope so) Now the function checks if there are any liquid block around pos, not just water blocks. This means that this works also for lava (and also for any other liquid block added in the future as long as they keep using `liquidtype` "source" or "flowing").

@HybridDog I've seen that with `buildin_item` mod the items droped into lava or in the path of flowing lava are destroyed. However, the placed blocks in front of flowing lava, like grass, remains in place and also they never burn as expected. I think that we could do something similar with flowing lava like you did in `strong_water` but burning/destroying the items. Do you know if this has been fixed before or do you have any other idea of how we can handle this? Thank you.
(To fix this issue and adding some flame efect when lava destroys the droped items and it will be almost perfect ;P)

**Comment by HybridDog** [comment]
>However, the placed blocks in front of flowing lava, like grass, remains in place and also they never burn as expected.

Burning nodes belongs to the fire mod, which has a setting to disable fire because minetest fire is cruel.

>[Add] some flame efect when lava destroys the [dropped] items

nice idea, maybe a smoke particle

**Comment by TomasJLuis** [comment]
@BlockMen I've forked the project and updated all the code in my branch. If you agree I could close these 3 pull requests and open just one with all the changes. I'm very sorry for the mess.

**Comment by BlockMen** [comment]
No problem. Yes, a clean PR would be better. Also, don't forget the option for MT-styled if you plan to add the check there aswell.

**Pull request closed without merging**
